CREATE TABLE "ticket_categories" (
	"id" serial PRIMARY KEY NOT NULL,
	"tenant_id" integer NOT NULL,
	"department_id" integer NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_subcategories" (
	"id" serial PRIMARY KEY NOT NULL,
	"tenant_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tickets" ADD COLUMN "category_id" integer;--> statement-breakpoint
ALTER TABLE "tickets" ADD COLUMN "subcategory_id" integer;--> statement-breakpoint
ALTER TABLE "ticket_categories" ADD CONSTRAINT "ticket_categories_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_categories" ADD CONSTRAINT "ticket_categories_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_subcategories" ADD CONSTRAINT "ticket_subcategories_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_subcategories" ADD CONSTRAINT "ticket_subcategories_category_id_ticket_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."ticket_categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ticket_categories_name_lower_unique" ON "ticket_categories" USING btree ("department_id",lower("name"));--> statement-breakpoint
CREATE UNIQUE INDEX "ticket_subcategories_name_lower_unique" ON "ticket_subcategories" USING btree ("category_id",lower("name"));--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_category_id_ticket_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."ticket_categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_subcategory_id_ticket_subcategories_id_fk" FOREIGN KEY ("subcategory_id") REFERENCES "public"."ticket_subcategories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
-- Backfill: every existing organization gets the default IT, Admin and HR departments (src/server/db/defaults.ts).
INSERT INTO "departments" ("tenant_id", "name", "is_public") SELECT "id", 'IT', true FROM "tenants" ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "help_topics" ("tenant_id", "name", "department_id", "sla_plan_id") SELECT d."tenant_id", 'IT Support', d."id", p."id" FROM "departments" d JOIN LATERAL (SELECT "id" FROM "sla_plans" WHERE "tenant_id" = d."tenant_id" ORDER BY "id" LIMIT 1) p ON true WHERE lower(d."name") = lower('IT') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "ticket_categories" ("tenant_id", "department_id", "name") SELECT d."tenant_id", d."id", v."name" FROM "departments" d CROSS JOIN (VALUES ('Hardware'), ('Software'), ('Network & Connectivity'), ('Email & Communication'), ('Accounts & Access'), ('Security')) AS v("name") WHERE lower(d."name") = lower('IT') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "ticket_subcategories" ("tenant_id", "category_id", "name") SELECT c."tenant_id", c."id", v."name" FROM "ticket_categories" c JOIN "departments" d ON d."id" = c."department_id" JOIN (VALUES ('Hardware', 'Laptop / Desktop'), ('Hardware', 'Monitor & Peripherals'), ('Hardware', 'Printer & Scanner'), ('Hardware', 'Mobile Device'), ('Software', 'Installation Request'), ('Software', 'License Request'), ('Software', 'Application Error'), ('Software', 'Software Update'), ('Network & Connectivity', 'Internet / Wi-Fi'), ('Network & Connectivity', 'VPN'), ('Network & Connectivity', 'Network Drive / Shared Folder'), ('Email & Communication', 'Email Issue'), ('Email & Communication', 'Teams / Chat'), ('Email & Communication', 'Calendar'), ('Accounts & Access', 'New Account'), ('Accounts & Access', 'Password Reset'), ('Accounts & Access', 'Access Permission'), ('Accounts & Access', 'Account Locked'), ('Security', 'Virus / Malware'), ('Security', 'Phishing Email'), ('Security', 'Lost or Stolen Device')) AS v("category", "name") ON lower(c."name") = lower(v."category") WHERE lower(d."name") = lower('IT') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "departments" ("tenant_id", "name", "is_public") SELECT "id", 'Admin', true FROM "tenants" ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "help_topics" ("tenant_id", "name", "department_id", "sla_plan_id") SELECT d."tenant_id", 'Admin Request', d."id", p."id" FROM "departments" d JOIN LATERAL (SELECT "id" FROM "sla_plans" WHERE "tenant_id" = d."tenant_id" ORDER BY "id" LIMIT 1) p ON true WHERE lower(d."name") = lower('Admin') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "ticket_categories" ("tenant_id", "department_id", "name") SELECT d."tenant_id", d."id", v."name" FROM "departments" d CROSS JOIN (VALUES ('Facilities & Maintenance'), ('Office Supplies'), ('Transport & Travel'), ('Access Cards & Security'), ('Meeting Rooms & Events')) AS v("name") WHERE lower(d."name") = lower('Admin') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "ticket_subcategories" ("tenant_id", "category_id", "name") SELECT c."tenant_id", c."id", v."name" FROM "ticket_categories" c JOIN "departments" d ON d."id" = c."department_id" JOIN (VALUES ('Facilities & Maintenance', 'Electrical'), ('Facilities & Maintenance', 'Plumbing'), ('Facilities & Maintenance', 'Air Conditioning'), ('Facilities & Maintenance', 'Furniture'), ('Facilities & Maintenance', 'Cleaning'), ('Office Supplies', 'Stationery'), ('Office Supplies', 'Pantry Supplies'), ('Office Supplies', 'Printing Supplies'), ('Transport & Travel', 'Vehicle Request'), ('Transport & Travel', 'Travel Booking'), ('Transport & Travel', 'Hotel Booking'), ('Access Cards & Security', 'New Access Card'), ('Access Cards & Security', 'Lost Access Card'), ('Access Cards & Security', 'Visitor Pass'), ('Access Cards & Security', 'Parking'), ('Meeting Rooms & Events', 'Room Booking'), ('Meeting Rooms & Events', 'Event Arrangement'), ('Meeting Rooms & Events', 'Catering')) AS v("category", "name") ON lower(c."name") = lower(v."category") WHERE lower(d."name") = lower('Admin') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "departments" ("tenant_id", "name", "is_public") SELECT "id", 'HR', true FROM "tenants" ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "help_topics" ("tenant_id", "name", "department_id", "sla_plan_id") SELECT d."tenant_id", 'HR Request', d."id", p."id" FROM "departments" d JOIN LATERAL (SELECT "id" FROM "sla_plans" WHERE "tenant_id" = d."tenant_id" ORDER BY "id" LIMIT 1) p ON true WHERE lower(d."name") = lower('HR') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "ticket_categories" ("tenant_id", "department_id", "name") SELECT d."tenant_id", d."id", v."name" FROM "departments" d CROSS JOIN (VALUES ('Payroll & Salary'), ('Leave & Attendance'), ('Benefits'), ('Recruitment & Onboarding'), ('Employee Documents'), ('Training & Development'), ('Policies & Grievances')) AS v("name") WHERE lower(d."name") = lower('HR') ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "ticket_subcategories" ("tenant_id", "category_id", "name") SELECT c."tenant_id", c."id", v."name" FROM "ticket_categories" c JOIN "departments" d ON d."id" = c."department_id" JOIN (VALUES ('Payroll & Salary', 'Salary Query'), ('Payroll & Salary', 'Salary Certificate'), ('Payroll & Salary', 'Deductions'), ('Payroll & Salary', 'Reimbursement'), ('Leave & Attendance', 'Leave Request'), ('Leave & Attendance', 'Leave Balance'), ('Leave & Attendance', 'Attendance Correction'), ('Benefits', 'Medical Insurance'), ('Benefits', 'Allowances'), ('Benefits', 'Other Benefits'), ('Recruitment & Onboarding', 'New Hire Request'), ('Recruitment & Onboarding', 'Onboarding'), ('Recruitment & Onboarding', 'Probation'), ('Employee Documents', 'Experience Letter'), ('Employee Documents', 'Employment Letter'), ('Employee Documents', 'Employment Contract'), ('Employee Documents', 'ID / Visa Documents'), ('Training & Development', 'Training Request'), ('Training & Development', 'Performance Review'), ('Policies & Grievances', 'Policy Question'), ('Policies & Grievances', 'Complaint / Grievance'), ('Policies & Grievances', 'Resignation & Exit')) AS v("category", "name") ON lower(c."name") = lower(v."category") WHERE lower(d."name") = lower('HR') ON CONFLICT DO NOTHING;
